### ISSUE TITLE
Lastest version of sextractor not compatible

### ISSUE THREAD

**Issue by JyKlub** [spel-uchile/Star_Tracker#1]
Hi,
i am trying to run the project on my Ubuntu, however the latest version of sextractor seems to be 2.25, and when i use 'apt intall sextractor' this newest version would be installed, with which either the 'sex' or 'sextractor' command (which you have inside your test file) would not work. I also tried to compile the 2.19.5 version, however when i try ./configure command, there is this clapack.h not usable error, i have installed clapack and it works fine with a test.c program, can you maybe give a hint how i can resolve this? Either how i can use the newer version of sextractor or how i can compile the 2.19 version manually?
Thanks

**Comment by samuel-gutierrez** [comment]
Hi,
Thanks for your message. You can try with:
`source-extractor`
If you want the full code works, you will need to change this line in the code:
**sext = 'sextractor ' + imdir**
I hope this helps you.
I plan to address this issue in further versions of the software.
Best Regards,

Samuel

**Comment by JyKlub** [comment]
Hi Samuel,
Thanks for the solution, works fine for me.
Best Regards,

JY
