### ISSUE TITLE
Creating Catalogues

### ISSUE THREAD

**Issue by madenbr** [spel-uchile/Star_Tracker#2]
How did you create catalogue as normal and projected(which projection method)? And, what do the values ​​mean?

**Comment by samuel-gutierrez** [comment]
Hi,
Sorry for the late reply.
You can create a particular "normal" catalog by selecting a specific sky portion from the full catalog. I particularly use the Bright Star Catalogue (BSC). You can find the full BSC catalog in the repo as **bsc_4** or **bsc_6**.
The specific catalog segments that this algorithm uses can be found in the folder *RPI/Catalog*. The projection method is a standard one used in astronomy. It is described in the research paper shown in the **README** of this repo (https://ieeexplore.ieee.org/document/9179736).
Cheers,

Samuel
